### ISSUE TITLE
how to solve the below errors?

### ISSUE THREAD

**Issue by Dutchosintguy** [ZackAkil/video-intelligence-api-visualiser#10]
the video-intelligence has been working perfect for me until today. I am getting this error when i run the python script, any tips how to solve this?

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Requested entity was not found."
	debug_error_string = "{"created":"@1666866950.739890000","description":"Error received from peer ipv6:[2a00:1450:400e:80e::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1064,"grpc_message":"Requested entity was not found.","grpc_status":5}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_video_intelligence.py", line 44, in <module>
    operation = video_client.annotate_video(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/cloud/videointelligence_v1/services/video_intelligence_service/client.py", line 428, in annotate_video
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.NotFound: 404 Requested entity was not found.`

**Comment by Dutchosintguy** [comment]
Update: solved by setting up a dedicated venv folder and use that as source
